# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordResetCode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordResetCodeTime',
            field=models.DateTimeField(null=True),
        ),
    ]
