# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_auto_20171203_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordResetCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwordResetCodeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
